[project]
name = "datacheck"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["openpyxl>=3.1", "pyyaml>=6.0"]

[project.scripts]
datacheck = "datacheck:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
